---
title: "Computation for Linguists"
subtitle: "LaTeX, Day 3 (cont.) — Citations & Bibliography"
date: "November 16, 2026"
author: "Dr. Andrew M. Byrd"
format:
  revealjs:
    css: header_shrink.css
    theme: beige
    slide-number: true
    center: true
    toc: true
    toc-title: "Plan for the Day"
    toc-depth: 1
editor: visual
---

# Finishing up Citations

## Additional Features: Citations

-   Citations in LaTeX will refer to a .bib file

-   Let's create one in our "301-LaTeX-practice" project folder

-   Call this .bib file "refs.bib"

## Additional Features: Your First .bib

```{latex}
@article{smith2017,
    author = {Smith, John},
    title = {Some paper},
    year = {2017},
    journal = {Journal of Research},
    volume = {2},
    number = {1},
    pages = {1--69}
}

@book{knuth1986,
  author    = "Donald E. Knuth",
  title     = "The {TeX} Book",
  year      = "1986",
  publisher = "Addison-Wesley Professional",
  address   = "Massachusetts"
}
```

## Wait, This Looks Familiar...

-   Compare a `.bib` entry to a Python dictionary:

```python
knuth1986 = {
    "author": "Donald E. Knuth",
    "title": "The TeX Book",
    "year": "1986",
    "publisher": "Addison-Wesley Professional",
}
```

-   Same idea: a set of `key = value` pairs, all describing one thing.
-   If you can build a dict, you can read (and write) a `.bib` entry.

## Additional Features: Citations

-   With these two references now in the system, let's practice citing them.

-   Edit your preamble with the following text, after the **documentclass** command.

```         
\documentclass{article} 
\usepackage{natbib} 
\bibliographystyle{apalike} 
\begin{document}
```

## Additional Features: Citations

-   End your document as follows:

```         
\bibliography{refs}  
\end{document}
```

## Additional Features: Citations

```{latex}
\documentclass{article}
\usepackage{natbib}
\bibliographystyle{apalike}

\begin{document}
\title{My First Document}
\author{My Name}
\date{December 6, 2017}
\maketitle

\section{Introduction}
 This is the introduction.\cite{smith2017}
\section{Methods}
\subsection{Stage 1}
The first part of the methods.\nocite{knuth1986}
 \subsection{Stage 2}
The second part of the methods.\cite[p. 215]{smith2017}
 \section{Results}
 Here are my results \citep{knuth1986,smith2017}.
 
\bibliography{refs} 
\end{document}
```

-   Copy the above code and run it in your project tex file.

## To Do at Home: Zotero

-   A *much* more user-friendly reference platform is Zotero.

-   Click here to sign up for the platform or log into your account.

-   Add at least one reference if you do not have one already.

-   Select all of the references to export

-   Click the "upwards arrow" icon

-   You now have a .bib file!

